[general]
static=yes
writeprotect=no

[from-internal]
; The Echo Test Application
exten => 200,1,Answer()
 same => n,Playback(hello-world)
 same => n,Echo()
 same => n,Hangup()

; Normal 4-digit extension routing
exten => _XXXX,1,NoOp(Call coming from ${CALLERID(num)} to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Playback(vm-nobodyavail)
 same => n,Hangup()
